### DISCUSSION TITLE
NEED HELP - Not understanding how to create the template sensor

### DISCUSSION THREAD

**Discussion by aries223** [moralmunky/Home-Assistant-Mail-And-Packages#1033] [Q&A]
Can someone show me, or point me to instructions on how to create the template sensor [shown here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Mail-Summary-Message) please, thanks

**Comment by aries223** [comment]
Bump..

**Comment by firstof9** [comment]
The instructions are in your link.

**Reply by aries223** [reply]
Not the "how to create a sensor" part...

**Reply by firstof9** [reply]
```
Add to the sensor: portion of the configuartion.yaml.
```

**Reply by aries223** [reply]
What configuration.yaml?

**Reply by firstof9** [reply]
For home assistant.

**Reply by aries223** [reply]
Where?

The HA configuration.yaml has no "sensor:" part in it. There is no 'configuration.yaml' in the "Mail-And-Packages" directory

**Reply by firstof9** [reply]
You have to add it in. Technically that's the old way.
The new way is under a new `templates:` section.

https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors

**Reply by aries223** [reply]
So like this?

```# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
- platform: template
  sensors:
    mail_deliveries_message:
      friendly_name: "Deliveries Summary"
      value_template: > 
        {# Deliveries Sentence #}
          {% macro deliveries_sentence() -%}
                {%- if states("sensor.mail_usps_mail")|int(0) == 0 -%}
         etc, etc, etc```

**Reply by firstof9** [reply]
close, more like:
```yaml
sensor:
  - platform: template
    sensors:
      mail_deliveries_message:
        friendly_name: "Deliveries Summary"
        value_template: > 
          {# Deliveries Sentence #}
            {% macro deliveries_sentence() -%}
                  {%- if states("sensor.mail_usps_mail")|int(0) == 0 -%}
  ...
  ```
  Spacing matters.
