### DISCUSSION TITLE
mail and packages logs

### DISCUSSION THREAD

**Discussion by tismofied** [moralmunky/Home-Assistant-Mail-And-Packages#700] [General]
I have 2 folders of this log like this. Is this normal?
![image](https://user-images.githubusercontent.com/90809124/181795813-4eba9be1-a507-4414-8f0c-b5418088a7f9.png)

**Comment by firstof9** [comment]
That would be normal if you've left debugging enabled.

**Reply by tismofied** [reply]
I might have. How can I disable it ? or is that not advisable?

**Comment by firstof9** [comment]
change to something like:
```yaml
logger:
  default: warning
  logs:
    custom_components.mail_and_packages: error
```
in configuration.yaml
