### ISSUE TITLE
[Feature Request] Add Image variant - static grid

### ISSUE THREAD

**Issue by SeanPM5** [moralmunky/Home-Assistant-Mail-And-Packages#1050]
**Is your feature request related to a problem? Please describe.**
Was revamping my mail and packages automation and template sensors today and had an exciting idea to describe/summarize mail contents using [LLM Vision](https://github.com/valentinfrlch/ha-llmvision) and Gemini. 

I got it mostly working (shared my script below), but the current formats provided by Mail & Packages integration (a `.gif` or .`mp4` that takes five seconds to cycle between each envelope) aren't quite ideal for this use case. Some LLM's won't accept those formats, others will time out especially if you have a bunch of mail. If you have ten pieces of mail that'd be 50 seconds of video to process.

Came up with a sorta solution to use FFMPEG and split out the camera into a static image in grid format: `ffmpeg -i usps_camera.gif -r 0.20 -filter_complex "tile=2x6:padding=10:color=black" mail_grid.png`

Looks something like this:
![Image](https://github.com/user-attachments/assets/ab9bab00-503f-44e9-a81e-1318b5b23c4e)

This works _perfectly_ in LLM Vision to analyze the contents, much faster and accurate. But it requires manual work, not sure how to automate this process. And even if I could, this image wouldn't be cleaned up when the `mail_image_system_path` sensor changes etc so it'd be leaving cruft behind. Would be nice if this was an opt-in option or something to generate an image like this along with the other ones.

Aside from this particular use case (LLM summary) this would still be useful addition IMO, for example a wall-mounted tablet mail view where you could see today's mail at a quick glance without waiting a minute for it to cycle through ten pieces of mail.

**Describe the solution you'd like**
A static image with a grid of all todays mail, similar to example screenshot above.

There's already two files generated:
`e0116f35-6c88-4cd7-ac52-763f9a12f8ec.gif`
`e0116f35-6c88-4cd7-ac52-763f9a12f8ec.mp4`

This would be a third image:
`e0116f35-6c88-4cd7-ac52-763f9a12f8ec_grid.png`

**Describe alternatives you've considered**
Vertically or horizontally stacked image of mail rather than a grid

**Additional context**
~~Below is the mostly working script, it will analyze the first envelope or two but then stop. But when giving it the static image grid it works perfectly.~~

Updated with new fully working script for `0.4.3-b3` !

```
script:

  analyze_mail:
    alias: "Mail - Analyze Incoming Mail"
    icon: mdi:mailbox
    sequence:
      - variables:
          incoming_mail: null

      - action: llmvision.image_analyzer
        response_variable: incoming_mail
        data:
          include_filename: false
          max_tokens: 50
          temperature: 0.2
          message: >-
            These are envelopes, only want to know who sent it and who it’s addressed to.
            - Only mention first names (Sean) and not last names (Mooney)
            - Separate each person with a semicolon, last person/sentence ends with a period instead
            - Include EVERY piece of mail. Pay close attention to the recipient as some pieces of mail could appear identical/duplicate but be addressed to different people. That needs to be properly listed in their section.
            - Don't include any other words besides the mail information. 
            - Give each person one sentence describing their mail (example output: "Bart has mail from Verizon; Marge has mail from Hyundai, AT&T; Lisa has mail from Xfinity.")
            - Ensure that each persons mail is grouped together, not spread apart. Make sure each unique envelope/piece of mail is comma separated. Semicolons are only used for indicating a different persons mail.
            - Attempt to fit the entire message within a 255 character limit while still ensuring accuracy. Make sure each unique envelope is listed.

          provider: 01JHSF308TKB7W573TM4Z4J3M7
          image_file: >-
            {{ states('sensor.mail_grid_image_path') }}

      - parallel:
        # Create a helper with this name to store as text, can use this to display in dashboards etc
        - action: input_text.set_value
          data:
            entity_id: input_text.incoming_mail_description
            value: "{{ incoming_mail.response_text }}"

        - alias: "Phone notification"
          continue_on_error: true
          action: notify.mobile_app_seans_iphone
          data:
            title: "📬 Today's Mail and Packages"
            message: "{{ incoming_mail.response_text }}"
            data:
              url: /main-dashboard/exterior
              group: "mail_packages"
              tag: "mail_upcoming_llm_test"
              push:
                interruption-level: time-sensitive
                sound:
                  name: "Alert_ReminderDue_Haptic.caf"
                  volume: 0.9
                category: camera
              entity_id: camera.mail_usps_camera
              actions:
                - action: "OPEN"
                  title: "View Mail Dashboard"
                  uri: "homeassistant://navigate/main-dashboard/exterior"
                  icon: "sfsymbols:chevron.right.circle.fill"
```

Example notification (when given the static grid image):
![Image](https://github.com/user-attachments/assets/f609fd93-13e3-426e-80ca-fa35a7dc5252)

**Comment by firstof9** [comment]
Let me see what I can do about adding an option for doing an additional image.

**Comment by firstof9** [comment]
Give `0.4.3-b3` a whirl, there's a new checkbox in the configuration to tell it to generate the grid image.

**Comment by SeanPM5** [comment]
Awesome, thanks a lot, this is a killer feature. Just tried it out and it works perfectly so far. Will continue to test over the next few days with different amounts of mail (only had 2 pieces today) but so far so good.

Only minor thing thing I've noticed is that when reconfiguring the integration and checking the box to generate the grid image, the entity didn't appear automatically, I had to manually enable it from the device info page. Not sure if that's expected behavior or not. 

Updated LLM prompt for the new grid image (edited the full script above with this too, working example for `0.4.3-b3`):

```
action: llmvision.image_analyzer
response_variable: incoming_mail
data:
  include_filename: false
  max_tokens: 50
  temperature: 0.2
  message: >-
    These are envelopes, only want to know who sent it and who it’s addressed to.
    - Only mention first names (Sean) and not last names (Mooney)
    - Separate each person with a semicolon, last person/sentence ends with a period instead
    - Include EVERY piece of mail. Pay close attention to the recipient as some pieces of mail could appear identical/duplicate but be addressed to different people. That needs to be properly listed in their section.
    - Don't include any other words besides the mail information. 
    - Give each person one sentence describing their mail (example output: "Bart has mail from Verizon; Marge has mail from Hyundai, AT&T; Lisa has mail from Xfinity.")
    - Ensure that each persons mail is grouped together, not spread apart. Make sure each unique envelope/piece of mail is comma separated. Semicolons are only used for indicating a different persons mail.
    - Attempt to fit the entire message within a 255 character limit while still ensuring accuracy. Make sure each unique envelope is listed.

  provider: 01JHSF308TKB7W573TM4Z4J3M7
  image_file: >-
    {{ states('sensor.mail_grid_image_path') }}
```

Thanks again! 🎉
