### ISSUE TITLE
error using mail_and_packages

### ISSUE THREAD

**Issue by bmf7777** [moralmunky/Home-Assistant-Mail-And-Packages#15]
it seems this sensor. mail_usps_mail isn't defined ... i can't determine where it's get set . i've cloned this files twice but continue to get this error
 
any ideas ?

https://xxx/local/mail_and_packages/mail_and_packages.js?v=.01:25:18 TypeError: hass.states[this.config.mail] is undefined

**Comment by bmf7777** [comment]
i'm also get this error in my logs

2019-12-04 09:46:29 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform mail_and_packages
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 148, in _async_setup_platform
    task = async_create_setup_task()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 104, in async_create_setup_task
    platform.setup_platform,
AttributeError: module 'custom_components.mail_and_packages.sensor' has no attribute 'setup_platform'

i'm using 102.2

**Comment by firstof9** [comment]
This happens when the configuration is left in the config files, comment the lines in your configuration files and enter them via the integrations menu.

Later release will support both config and integration config.

**Comment by bmf7777** [comment]
i'm still getting TypeError: hass.states[this.config.mail] is undefined with sensor.mail_usps_mail not instantiated 
i loaded your package via integrations (HACS) first time i've used this method ... and it copied all the files over. i adjusted the config... (see below)
then added js resources to ui-lovelace.yaml .. HA recognizes the integration stating 
"You are using a custom integration for mail_and_packages blah blah."
i've got a lot of integrations, sorry that i can't figure this out - what i'm i doing wrong?
```
 - type: js
    url: /local/mail_and_packages/mail_and_packages.js?v=.01
```



```
mail_and_packages:
#  host: !secret mail_host
#  port: !secret mail_port
#  username: !secret mail_username
#  password: !secret mail_password
#  folder: 'Inbox'
#  image_output_path: !secret mail_image_output_path

################################################
## Sensors
################################################    

sensor:
  - platform: mail_and_packages
    host: !secret mail_host
#.   port: !secret mail_port Using Default Port
    username: !secret mail_username
    password: !secret mail_password
#    folder: 'Inbox' Using Deafult Folder
#     image_path: !secret mail_image_output_path Using Default Path 
```
