### ISSUE TITLE
ISSUE: Wiki example missing data

### ISSUE THREAD

**Issue by SeanPM5** [moralmunky/Home-Assistant-Mail-And-Packages#263]
**Describe the bug**
Not a bug in the custom component, but the [notification automation example on the Wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Example-Automations-and-Templates#notification-automation) is missing the sensor domain in the entity ID.

```
  trigger:
  #Trigger if mail or packages get updated
    - platform: state
      entity_id: sensor.mail_usps_mail
    - platform: state
      entity_id: mail_packages_in_transit
```
That last state trigger line should be `entity_id: sensor.mail_packages_in_transit`

(Also, there's another very minor typo in the opening paragraph, `configuartion.yaml` should be `configuration.yaml`)
