### ISSUE TITLE
Reduce Steps For Image Use

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#321]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- Reduce steps to display the mail image.
- Make the image file path and random image name more accessible
  - Standardize the image path
  - Make random image name default, eventually the only option
 by standardizing the path.
  - Create sensors that will provide the complete correct paths to use in the custom card, camera entities/cards, and notifications.

Needed:
- Internal absolute file path
- External /local/ path
- External URL path

**Standardize the GIF path to `[path to conig]/www/mail_and_packages/`**
 - Directory listing is forbidden. Saving the image here should be secure with the random name.

**Provide sensors that report the different paths needed in place of having the `image` attribute in sensor.mail_usps_mail**

- sensor.mail_usps_mail_image_system_path = [system config path]/www//mail_and_packages/[image name].gif
  - Automatically determine the `[system config path]` or change the field in the integration from `image path` to `config path`
  - Use a `local_file camera` then use this sensor in the automation to update the `file_path:`
    - The yaml for the automation would then be universal
  - Tried templating the local file camera `file_path:` directly so the automation wouldn't be required, but that didn't work. Maybe in the future this will work?
  - Could the integration create a camera sensor and call the service to update the camera `file_path:`?
  - The [generic camera](https://www.home-assistant.io/integrations/generic/) accepts templating in `still_image_url:`, details in the 'Camera component templating' area.

- sensor.mail_usps_mail_image_local_path = /local/mail_and_packages/[image name].gif
  - Could be hard coded in the custom card with just a toggle switch to turn it on or off
  - Reduce the number of fields in the custom card editor

- sensor.mail_usps_mail_image_url = [domain]/local/mail_and_packages/[image name].gif
  - Could negate having the sensor.mail_usps_mail_image_local_path
  - Can be used in notifications
  - Can be used in a future version of the custom card instead of text input field for the path
  - Can the internal/external domain be retrieved programmatically inside the integration?

**Describe alternatives you've considered**
This can be achieved with template sensors. Since the attribute will change based on the random image toggle switch, it will report either mail_today.gif or the random image name. This adds complication and additional work. Probably more assistance requests.

```
sensors:
    mail_gif_file:
      friendly_name: "Mail GIF file"
      value_template: "/config/www/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}"
        
    mail_gif_local:
      friendly_name: "Mail GIF local"
      value_template: "/local/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}"

    mail_gif_web:
      friendly_name: "Mail GIF web"
      value_template: "https://[domain redacted]/local/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}"
```
**Camera component templating**
Tried several ways to template a camera component but all failed. The generic seemed to be the solution since `still_image_url:` can be templated, but I couldn't get any internal server image to show, 500 internal errors. This could be my current set up, in the process of changing network to utilize VLANs. A gif from an outside source worked correctly.

```
camera:    
  - platform: local_file
  # Local doesn't like to be templated
    file_path: "{{ states('sensor.mail_gif_file') }}"
    name: mail_usps_sensor
    
  - platform: generic
    #Should work without the need of automation
    still_image_url: "{{ states('sensor.mail_gif_web') }}"
    content_type: image/gif
    name: mail_generic
```
