### ISSUE TITLE
Not picking up FedEx package as in transit

### ISSUE THREAD

**Issue by rpitera** [moralmunky/Home-Assistant-Mail-And-Packages#34]
V0.07, installed via HACS using latest version of documentation
HomeAssistant version - 0.105.3

Got an email notification from FedEx from trackingupdates@fedex.com with title:

**FedEx Shipment 45280775XXXX: Your package is on its way** 
(Number redacted, but if you need it give me a way to DM you.)

But no state change on sensor.packages_in_transit or sensor.mail_fedex_packages.  

Link to email (address/package number redacted): https://drive.google.com/file/d/1foXa0mYWvv71c2C_vMgr256dzyXCt3YG/view?usp=sharing

Expected behavior:  Sensors would increase from 0 to 1 in at least packages in transit.

**Comment by moralmunky** [comment]
The sensor doesn't look at or keep track of tracking numbers. Is this the only email you received about this package delivery? Did you get any with "Delivery scheduled for today" in the subject line?

**Comment by rpitera** [comment]
>The sensor doesn't look at or keep track of tracking numbers. 

I know that.  I was speaking about the email link I posted.  I wanted you to know that it was edited to show as REDACTED in the text in case you saw it or used it in parsing while testing.

>  Is this the only email you received about this package delivery?

Yes, so far.

> Did you get any with "Delivery scheduled for today" in the subject line?  

No, the delivery is scheduled for Tuesday, two days away.   Does it only parse delivery day messages?  I was under the impression that since there was a sensor.mail_fedex_delivering that this would be fed by in transit emails.  Am I misunderstanding it's function?

**Comment by moralmunky** [comment]
Yes, it is only looking at current day in transit or delivered email messages. We have seen vendors adding additional emails subjects lines and using multiple subject lines for the same type of notification. There is not way of us knowing until a users reports or we receive a message that is different so we can add it to the subject line search for a particular package vendor. 

**Enhancement:**
Fedex
Email Address: Same
new subject line for in transit count 'Your package is on its way'

**Comment by rpitera** [comment]
I had a feeling I might have misunderstood; thanks for clearing that up for me.  I really appreciate the hard work you, @firstof9 and @FuzzyMistborn have put into this; it's a great solution.  The updated docs as so much clearer now as well.  Thanks to all and to you for your help.

**Comment by firstof9** [comment]
I'm thinking a regex like:
```FedEx Shipment /^[0-9]{15}$/: Your package is on its way``` for these types of email.

**Comment by aneisch** [comment]
The subject I got today for an incoming delivery was identical to the above, but the tracking is 12 digits. According to [Stack Overflow](https://stackoverflow.com/a/5024011) Fedex can be 12, 15 or 20 digits. So maybe a range of 12-20

`FedEx Shipment /^[0-9]{12,20}$/: Your package is on its way

**Comment by moralmunky** [comment]
Maybe it would be easier, and long term sustainable, if it matching if contains ‘Your package is on its way’ instead of accounting to the entire headline?

**Comment by rpitera** [comment]
Well, now I am totally confused.  Today I got a FedEX email with the subject "FedEx Shipment 45280775XXXX: Your package is scheduled for delivery today" but still nothing showing in the sensors.  In fact nothing on ANY of the sensors.

Now I recently reinstalled everything because in another issue, I was told that the sensor templates in the old package install version was deprecated and no longer necessary.  So I commented everything out, moved my old /custom_components/mail_and_packages folder to a safe location and reinstalled everything from the latest doc instructions.

I didn't have any mail for a few days so I didn't think anything was wrong.  But today I have USPS mail and nothing was showing up at all.  Even the sensors weren't there.  So I reversed my procedures and uncommented out my previous template sensors and my mail is showing again, as is the camera image and all my other sensors.  But FedEx sensors are _still_ showing zero states.

So while I am glad I've got USPS mail/packages showing properly, I am thoroughly confused about what the proper procedures/code versions are.  What am I doing wrong here?

**Comment by moralmunky** [comment]
@rpitera, If you are using the current files in the repository you will find in Home Assistant  going to 'Developer Tools' > 'States' that if you type in mail_ in the filter entities field you should see all of the entities the custom component is creating, below.

- sensor.mail_fedex_delivered
- sensor.mail_fedex_delivering
- sensor.mail_fedex_packages
- sensor.mail_packages_delivered
- sensor.mail_packages_in_transit
- sensor.mail_updated
- sensor.mail_ups_delivered
- sensor.mail_ups_delivering
- sensor.mail_ups_packages
- sensor.mail_usps_delivered
- sensor.mail_usps_delivering
- sensor.mail_usps_mail
- sensor.mail_usps_packages

If you do not see all of these, there is something wrong. The the front end card, the previously included Lovelace card is depreciated and is no longer supported. The readme for this repository provides three options for adding the sensors to the front end. Option 3 doesn't require any additional customization of HASS and was recently updated to correct a few mistakes.

**Comment by moralmunky** [comment]
@firstof9 I think the subject line search does match with 'contains' because originally I only had 'Your package has been delivered' as the subject to match and I have had the sensor count them. All my fedex emails subjects have the tracking number in the beginning.

**Comment by moralmunky** [comment]
Reviewing the code, there is still a mismatch in the subject line

We are looking for FEDEX_Delivering_Subject = 'Delivery scheduled for today' which is what the subjects were for most of 2019.

'Your package is on its way' is for future deliveries and we won't track this.

'Your package is scheduled for delivery today' seems to be the new subject starting end of November/December 2019. There is no way of telling if they changes all day of subject lines to this or if they are testing it. We'll have to add this in addition to the old one.

This will solve then issue of the day of notification not being counted.

**Comment by rpitera** [comment]
>If you do not see all of these, there is something wrong. 

Yes, I agree.  But after following all the instructions step by step I'm at a loss as to what is the problem.

Here is the steps that I took when I reinstalled from using the 'deprecated' method:

1. Commented out all of the template sensors I had originally created.  Added the one template sensor for the mail deliveries message above the commented code.
2. Moved the deprecated version folder of /custom_components/mail_and_packages/ from my HA server to a safe location on my PC.  (This left me with no mail_and_packages folder in custom_components, by design since using the HACS install should replace it.) Did the same with the contents of /www/mail_and_packages, reserving my originals in the same safe location just in case.
3. Added the camera entity to my cameras.yaml and the automation.
4. Removed my previous integration entry and restarted HA
5. Went to integrations, added mail and packages.  Altered the path to reflect the proper one for a HASS.IO (now HomeAssistant) installation.  Received a successful integration message.
6. Pasted code from first example (after fixing the indents) into my test page in Lovelace.  For good measure, one last restart of HA.

Do you guys see anything I missed or did incorrectly?  I'd be glad to try again - I've saved everything so I can go back - all I know is that it didn't work and no sensors seemed to be created.  I checked the folder structure and it looks correct - and I am using the latest version of HACS so the folders bug can't be at fault here.  The card displayed just fine; it's the sensor creation that seems to be at issue in my case.

In the meantime reverting back to the deprecated method at least is giving me sensors and USPS mail correctly (including the camera) so I can be sure that my other configurations (mail setup for each service and the imap host setup using gmail) is correct, so that can be ruled out.

I'm open to suggestion and testing.  And since I still have the mail in there today, there's something to test against.

**Comment by moralmunky** [comment]
Can you update the logger portion of your configuration.yaml (or wherever you have logger defined in your configuration) and supply the output?

logger:
  default: warning
  logs:
    custom_components.mail_and_packages: debug
    homeassistant.components.sensor: debug

I am not familiar with the HACS installation method. Is the /www/mail_and_packages/ folder created and filled with any files after the integration is setup?

**Comment by rpitera** [comment]
>Can you update the logger portion of your configuration.yaml (or wherever you have logger defined in your configuration) and supply the output?

I'll have to remove the deprecated version first and reinstall but I'd be glad to.

>I am not familiar with the HACS installation method. Is the /www/mail_and_packages/ folder created and filled with any files after the integration is setup?

It must, because the vertical stack in card option 1 showed the no mail.gif file properly.  I could just as easily reinstall this using the manual method though if you prefer.

>One this is that the first option for Lovelace does require a custom card is also added to Home Assistant.

Yeah, I think you may not be getting me here - the card displayed fine.  I use custom cards all the time and already had vertical-stack-in-card installed.  I'm way past the basics.  I use a LOT of custom cards and custom CSS in my Lovelace card styling.  I've also been at this since 2013 so I know my way around... ;-)  Also do a lot of beta testing for other devs.

When I say I didn't see the sensors, I'm talking about dev > states where the actual sensor entities would be found. (I'm sorry if this wasn't clear; I just assumed you knew where I was looking for sensors.)  Using the previous installation method I laid out in steps, I didn't have any sensors from mail & packages at all.  They should have been created around line 64 in sensor.py but never were.  Hopefully reinstalling and running debug mode for the integration will reveal more.

I'm going to try uninstalling from HACS and just going manual this time.   I'll reclone the repo and make sure I have all the latest.  Will update you soon.

**Comment by rpitera** [comment]
Made real progress here.  I now have sensors in dev > states AND the fedex sensors are showing with values for in transit and delivered.  I think I will have to modify the deliveries sentence template a bit to include FedEx and UPS though; it seems somehow wrong to me that the sentence doesn't account for them.

Manual seems to be the way to go; maybe something wrong with the HACS install json?  My structure seemed fine and comparable to the current working version I just installed, but given that it is the only real difference between the two attempts, hacs.json is suspect.  It is also a viable reason my previous deprecated version 'worked' as it was also manually installed.  (I say 'worked' because that version didn't have any values for the fedex sensors like I have now.)

I only chose it because it was the "highly recommended" method.

**Comment by firstof9** [comment]
Note for the regex here:
```^FedEx Shipment [0-9]{12,20}:.*$```
Should match anything after the tracking #

**Comment by moralmunky** [comment]
I don't think it is needed. Pretty sure it the search counts subjects that contain our phrase not exact matches.

**Comment by rpitera** [comment]
BTW, until I can get a chance to work out the templating for a delivery sentence for FedEX/UPS I just added a glance card to the stack and styled it a bit.  I'll share it here in case you can use it...


```
  - type: custom:vertical-stack-in-card
    title: Mail & Package Tracking
    cards:
      - type: picture-glance
        camera_image: camera.mail_usps
        entities: []
      - type: entity-filter
        state_filter:
          - operator: ">"
            value: '0'
        entities:
          - entity: sensor.mail_usps_mail
            name: "Today's Mail"
          - entity: sensor.mail_packages_in_transit
            name: "Today's Package Delivery"
          - entity: sensor.mail_usps_delivering
            icon: 'mdi:package-variant-closed'
            name: USPS
          - entity: sensor.mail_fedex_delivering
            icon: 'mdi:package-variant-closed'
            name: FedEx
          - entity: sensor.mail_ups_delivering
            icon: 'mdi:package-variant-closed'
            name: UPS
          - entity: sensor.mail_updated
            state_filter:
              - operator: "regex"
                value: 20
      - type: entities
        entities:
          - entity: sensor.mail_deliveries_message
            icon: mdi:bullhorn
            name: ' '
      - type: glance
        title: ━━ UPS/FedEX ━━━━━━━━━━━━
        style: |
          ha-card {
            font-size: .80em;
          }
          ha-card div.card-header {
            font-size: 1.5em;
            color: cyan;
          }
        columns: 3
        entities:
          - entity: sensor.mail_ups_delivering
            name: UPS In Transit
          - entity: sensor.mail_ups_delivered
            name: UPS Delivered
          - entity: sensor.mail_ups_packages
            name: All UPS Packages
          
          - entity: sensor.mail_fedex_delivering
            name: FedEX in transit
          - entity: sensor.mail_fedex_delivered
            name: FedEX Delivered
          - entity: sensor.mail_fedex_packages
            name: All FedEX Packages
```
