### ISSUE TITLE
Update WIKI examples

### ISSUE THREAD

**Issue by mgriffin13** [moralmunky/Home-Assistant-Mail-And-Packages#372]
Now that 0.3.0 has been released, you might need to update some of your wiki examples.

For instance, my camera definition had to change to this:

```yaml
camera:
  - platform: local_file
    file_path: /config/images/mail_and_packages/overlay.png
    name: mail_usps
```

My image change automation had to change to this:

```yaml
alias: Update USPS Mail Camera
trigger:
  - platform: state
    entity_id: sensor.mail_updated
  - platform: homeassistant
    event: start
action:
  - service: local_file.update_file_path
    data:
      file_path: '{{ states(''sensor.mail_image_system_path'') }}'
    entity_id: camera.mail_usps
mode: single
```
