### ISSUE TITLE
ISSUE: Camera image switching back to "no mail"

### ISSUE THREAD

**Issue by drguitarum2005** [moralmunky/Home-Assistant-Mail-And-Packages#453]
**Describe the bug**
I followed this guide exactly with "Option 2" for displaying the USPS image from my daily summary. It will show the correct mail image for a bit but will change to the default "No Mail" image every 15 minutes or so.

**Environment (please complete the following information):**
 - OS: Home Assistant OS
 - Type of device: Proxmox on Surface Pro 3
 - Home Assistant version: 2021.5.5
 - Hassio/Docker/Core? Core

![image](https://user-images.githubusercontent.com/15187807/119857526-446b5e80-bed9-11eb-8036-10d4c0c77072.png)

Configuration.yaml:
```
camera:
  - platform: local_file
    file_path: /<config path>/custom_components/mail_and_packages/mail_none.gif
    name: mail_usps
    
automation:
  - alias: "Update USPS Mail Camera Path on Hass Restart"
    trigger:
      - platform: state
        entity_id: sensor.mail_updated
      - platform: homeassistant
        event: start
    action:
      - service: local_file.update_file_path
        data_template:
          entity_id: camera.mail_usps
          file_path: "{{ states('sensor.mail_image_system_path') }}"
```
