### ISSUE TITLE
ISSUE:  could not read camera mail_usps image from /home/homeassistant/.homeassistant/images/mail_and_packages/mail_today.gif

### ISSUE THREAD

**Issue by ttaidapos** [moralmunky/Home-Assistant-Mail-And-Packages#77]
**Describe the bug**
See attached error

**Environment (please complete the following information):**
 - OS: Raspbian
 - Type of device: RPi4
 - Home Assistant version: 0.106.5
 - Hassio/Docker/Core?  VM
 - Component version: 0.1.2-1

**Screenshots**
![Capture](https://user-images.githubusercontent.com/27898709/77684920-a2fd1b80-6f68-11ea-975b-564e619d9e4a.PNG)

**Additional context**
Using chrome, if I refresh the page it goes away.  Using duckdns and ACME.SH for certificate.

**Comment by ttaidapos** [comment]
After further investigation, I removed the jpg and gif from /home/homeassistant/.homeassistant/custom_components/mail_and_packages/, restarted hass, and the mail_none.gif was not rendering at all.  Added the two images back and it started working again.  Somewhere in the code it's still referencing install directory vs. /home/homeassistant/.homeassistant/images/mail_and_packages/.

**Comment by moralmunky** [comment]
**Addressing the mail_none.gif and image-no-mailpieces700.jpg**
These two images are required and must stay in the integrations directory. When there are no mail images found in the email, the mail_none.gif is then copied to the path specified in the configuration options as mail_today.gif.

When the informed delivery email has the image stating that there are more mail pieces that USPS does not have images for, the component adds the image-no-mailpieces700.jpg to the animated gif which is written to the path specified in the configuration options as mail_today.gif.

Removing the two files as you described, the expected outcome is that the integration will break. So your experience is correct when deleting those files.

The camera component from HASS does not work very well in Safari and often does not show an image, but for me it seems to consistently work in Chrome. You can try using a picture entity card with the camera view set to live to see if that helps.

**Comment by ttaidapos** [comment]
Thanks for the explanation.  The other thing I noticed that this produces the famous "Login attempt or request with invalid authentication from x.x.x.x" error.  When I removed the pics from the install directory those errors didn't show up in the log.  Once I added them i got the errors again.

**Install Directory**
```
pi@hass:/home/homeassistant/.homeassistant/custom_components/mail_and_packages $ ls -lha
total 148K
drwxr-xr-x 3 root          root          4.0K Mar 26 16:18 .
drwxr-xr-x 4 root          root          4.0K Mar 23 19:28 ..
-rw-r--r-- 1 homeassistant homeassistant 4.3K Mar 20 08:22 config_flow.py
-rw-r--r-- 1 homeassistant homeassistant 1.2K Mar 20 08:22 const.py
-rw-r--r-- 1 homeassistant homeassistant  44K Mar 26 14:27 image-no-mailpieces700.jpg
-rw-r--r-- 1 homeassistant homeassistant 1.6K Mar 20 08:22 __init__.py
-rw-r--r-- 1 homeassistant homeassistant  41K Mar 26 14:27 mail_none.gif
-rw-r--r-- 1 homeassistant homeassistant  274 Mar 20 08:22 manifest.json
-rw-r--r-- 1 homeassistant homeassistant  28K Mar 20 08:22 sensor.py
drwxr-xr-x 2 homeassistant homeassistant 4.0K Mar 20 08:22 .translations
```
**Images Directory**
```
pi@hass:/home/homeassistant/.homeassistant/images/mail_and_packages $ ls -lha
total 140K
drwxr-xr-x 2 homeassistant homeassistant 4.0K Mar 26 16:15 .
drwxr-xr-x 4 homeassistant homeassistant 4.0K Mar 25 23:16 ..
-rw-r--r-- 1 homeassistant homeassistant  44K Mar 24 08:00 image-no-mailpieces700.jpg
-rw-r--r-- 1 homeassistant homeassistant  41K Mar 24 08:01 mail_none.gif
-rw-r--r-- 1 homeassistant homeassistant  41K Mar 26 16:15 mail_today.gif
```

**Error**
**Log Details (WARNING)
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:74
Integration: http (documentation, issues)
First occurred: 2:53:56 PM (1 occurrences)
Last logged: 2:53:56 PM

Login attempt or request with invalid authentication from 192.168.50.1**

**Comment by moralmunky** [comment]
I also saw those when I had the camera local file set up. I no longer use the camera component from Home Assistant and have not notices these.

I would suggest testing by removing the local file component you have set up for mail and packages and create a new one with an image of your choosing. If the same errors appear it should be reported to Home Assistant.

**Comment by jcconnell** [comment]
I had a similar experience when I installed via HACS.

The camera example states to add:
```
file_path: /config/images/mail_and_packages/mail_today.gif
 ```

However, when installing via HACS we aren't told to create this directory. To resolve, I created the directory '/home/homeassistant/.homeassistant/images/mail_and_packages/` and ensured it was owned by the user running Home Assistant. I also changed the `file_path` in the configuration to the same path. After a restart, everything was working as expected.

**Comment by firstof9** [comment]
> when installing via HACS we aren't told to create this directory.

The component creates the directory if it doesn't exist.

**Comment by jcconnell** [comment]
In my case, the directory was not created.

**Comment by ttaidapos** [comment]
I'm using images for other cards etc. and don't see the same problem.  Can you review the permissions from my post above and if they're correct?

**Comment by firstof9** [comment]
> Can you review the permissions from my post above and if they're correct?

Permissions look fine global read permissions (644).

**Comment by moralmunky** [comment]
@ttaidapos Are you able to see the images in HA but are just getting log errors? Did you try to remove the camera card and try the picture entity card instead?

**Comment by ttaidapos** [comment]
Removed older card and trying picture entity.  Still seeing this issue and haven't seen it with other integrations.  I still have a hunch it has to do something with this integration and not hass core.  I'll report back with the picture entity card.

**Here's the error**
```
Log Details (WARNING)
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:74
Integration: http (documentation, issues)
First occurred: April 11, 2020, 12:10:31 AM (10 occurrences)
Last logged: April 12, 2020, 7:10:14 PM

Login attempt or request with invalid authentication from 192.168.50.1
```

**here's the card that I removed**
```
cards:
  - aspect_ratio: 35%
    camera_image: camera.mail_usps
    camera_view: live
    entity: sensor.mail_usps_mail
    name: Today's Mail
    type: picture-entity
  - entities:
      - entity: sensor.mail_usps_delivered
        icon: 'mdi:package-variant'
        name: USPS Delivered
      - entity: sensor.mail_fedex_delivered
        icon: 'mdi:package-variant'
        name: FedEx Delivered
      - entity: sensor.mail_usp_delivered
        icon: 'mdi:package-variant'
        name: UPS Delivered
      - entity: sensor.mail_usps_delivering
        icon: 'mdi:package-variant-closed'
        name: USPS in Transit
      - entity: sensor.mail_fedex_delivering
        icon: 'mdi:package-variant-closed'
        name: FedEx in Transit
      - entity: sensor.mail_ups_delivering
        icon: 'mdi:package-variant-closed'
        name: UPS in Transit
      - entity: sensor.mail_updated
        name: Mail Updated
    state_filter:
      - operator: '>'
        value: '0'
    type: entity-filter
title: Mail Today
type: 'custom:vertical-stack-in-card'
```

**Here's the card i added**
```
type: picture-entity
entity: sensor.mail_packages_in_transit
aspect_ratio: 50%
camera_image: camera.mail_usps
```

**Comment by firstof9** [comment]
It's no the integration see here:
https://github.com/home-assistant/core/issues/23055

**Comment by ttaidapos** [comment]
Well that's great!  Thanks for this.

**Comment by firstof9** [comment]
I am trying their solution with the config changes:
```
    trusted_proxies:
      - 192.168.1.0/24
```
added to my http config.

**Comment by ttaidapos** [comment]
Picture-Entity doesn't produce this error.  I'm wondering if it's the 'custom:vertical-stack-in-card'?

**Comment by firstof9** [comment]
It has to do with the underlying code in the local file camera.

**Comment by firstof9** [comment]
I just confirmed that adding the ```trusted_proxies``` lines did resolve the ```Login attempt or request with invalid authentication from``` error messages.

**Comment by ttaidapos** [comment]
Alright here are my findings... and it does fix the issue.  What is not clear is if there's a level of risk associated with this configuration?  The only risk I can think of is someone getting access to your internal network AND THEN brute forcing your hass instance.  In theory, if you have MFA setup in hass you're good to go which is the case for me.  Otherwise, the scenario would be like this...
1. Man in the middle attack on your wifi to gain access, this is fairly easy for someone that really wants to get in.  If your wifi password is something easy and common in dictionary files, doesn't take long (hours).
2. After in your network, they need to find your hass instance which is also fairly simple.
3. Then they'll need to crack your hass password followed by MFA (the MFA part is not so hard with google authenticator)

Overall, this is highly unlikely assuming your ipban is set to true :) But even so, still highly unlikely :)  To summarize...
1. Set your hass password for all users
2. Configure MFA
3. Enable ipban
4. follow steps below :)
Use !include for your ipaddresses 

**Dependency**
You definitely need "use_x_forwarded_for: true" in order to use "trusted_proxies"

**YAML**
So your configuration.yaml should look similar to this...  If you want to list the whole subnet instead of having individual entries, then use the "/##" and listing the octet used, most often it's '24'.  For my configuration my entry is '192.168.50.0/24'.  Please note the zero is almost used here as a wildcard so any ip from 1-255 would be included.
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - #.#.#.#/##
    - #.#.#.#
```
The above produces a single IP error on restarts which is solved by using the following yaml...  Basically includes the loopback address of "127.0.0.1".  If you don't care for 1 error on restart, leave as is otherwise you'll need to include loopback address.  If you know the specific IPs that will be accessing hass and are static (even DHCPs usually issue the same IP unless your device is off for a long time) then you're better off and more secure.  You can have multiple entries as shown below.
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - #.#.#.#/##
    - #.#.#.#
```

**Using include files**
```
http:
  use_x_forwarded_for: true
  trusted_proxies: !include name_of_file.yaml
```
Create a new file with the 'sudo nano name_of_file.yaml' command and then list all your IPs in the file.
```
- 127.0.0.1
- #.#.#.#/##
- #.#.#.#
```
