### ISSUE TITLE
ISSUE: Amazon package automation not working

### ISSUE THREAD

**Issue by dnestico** [moralmunky/Home-Assistant-Mail-And-Packages#845]
**Describe the bug**
I have an automation to send me notifications for amazon packages but I have no idea why it will never work even though this addon does seem to be working and collecting the info when packages are delivered...

**Environment (please complete the following information):**
 - OS: Docker
 - Type of device: Laptop with unraid docker
 - Home Assistant version: 2023.9.2
 - Docker
 - Component version: Latest

**Logs**
None sorry

**Screenshots**
<img width="602" alt="Screenshot 2023-09-18 at 4 05 22 PM" src="https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/3034555/fd4c5ccd-49b7-4aea-b6d0-72cbea7b3308">

<img width="815" alt="Screenshot 2023-09-18 at 4 08 49 PM" src="https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/3034555/5e407e37-a8d7-48de-9027-cd176624e529">

**Additional context**
Here is my code:

```
alias: Mail Notif - Mail Delieveries GIF
trigger:
  - platform: state
    entity_id: sensor.mail_amazon_packages
  - platform: state
    entity_id: sensor.mail_amazon_packages_delivered
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ ((as_timestamp(now()) -
          as_timestamp(states.sensor.mail_amazon_packages.last_changed)) < 15
          and states('sensor.mail_usps_mail')|int > 0) }}
      - condition: template
        value_template: >-
          {{ ((as_timestamp(now()) -
          as_timestamp(states.sensor.mail_amazon_packages_delivered.last_changed))
          < 15 and states('sensor.mail_amazon_packages_delivered')|int > 0) }}
action:
  - delay: "00:00:20"
  - service: notify.davids_notify_devices
    data:
      title: Amazon Package Notification
      message: "{{ states('sensor.mail_amazon_packages_delivered')}}"
      data:
        attachment:
          url: "{{ states('sensor.mail_image_url') }}"
          hide-thumbnail: false
        apns_headers:
          apns-collapse-id: homeassistant-mail-update
        push:
          thread-id: homeassistant-mail
initial_state: true
```
